### ISSUE TITLE
Combined Tree-view in Main Pane

### ISSUE THREAD

**Issue by Toxijuice** [omeryanar/FileExplorer#16] opened 2022-11-09 02:57 UTC
This might be an odd request, as I've never actually seen it done in a file explorer. But I would love to see a mode where the main file explorer pane was a combination of the existing method of navigation, as well as a tree-view type explorer.

What I mean by that is: You would still navigate folders by double-clicking, which would open that folder, setting the current working directory. But then once that directory is open you would also be able to expand child folders of that directory in a tree-like manner.

The current problems with the navigation pane are that you can only see directories, no files. And when you drill very far down the tree becomes very unruly.  A combination of the two styles would solve those issues.

A feature like this might be a big ask, but I absolutely love what has been done with this FileExplorer so far, and would love to see it be capable of this.

**Comment by omeryanar** [comment] 2023-01-16 14:34
A very interesting request indeed. If I understood you correctly, you want something like this:
![TreeView](https://user-images.githubusercontent.com/34584700/212701804-c503228b-12aa-49f0-a5d5-2bdbcdd87d06.png)

I think this can be done, but I need to make sure all the interactions (drag/drop, copy/paste etc) still work.

**Comment by Toxijuice** [comment] 2023-01-16 18:22
That looks pretty much exactly like what I was describing!

**Comment by omeryanar** [comment] 2023-01-21 19:27
I've just published a version with a new layout type: Content
After some detailed testing, I will close this issue.
Thanks for the idea, I think it's a unique feature in similar apps

**Comment by DuckEater** [comment] 2023-02-12 23:51
> If I understood you correctly, you want something like this: ![TreeView](https://user-images.githubusercontent.com/34584700/212701804-c503228b-12aa-49f0-a5d5-2bdbcdd87d06.png)

It is unclear on your screenshot, but a long time missing feature of Windows is the ability to have both files and folders in a tree-view layout.
Sorry, I don't have time to compile and test your last release right now, but I greatly hope it offers that !

**Comment by DavidBevi** [comment] 2023-02-14 00:24
> [...] both files and folders in a tree-view layout. 
Feature present!
![IMG-20230214-WA0000](https://user-images.githubusercontent.com/61429850/218606082-35980ba0-dd50-46dd-82d6-e86c9d5e3739.jpg)

**Comment by omeryanar** [comment] 2023-02-14 17:48
> It is unclear on your screenshot, but a long time missing feature of Windows is the ability to have both files and folders in a tree-view layout. Sorry, I don't have time to compile and test your last release right now, but I greatly hope it offers that !

Yes, since the screenshot only shows the folders in the main pane, it may be a bit confusing. I've included this feature in the Readme file and added a more descriptive screenshot: https://github.com/omeryanar/FileExplorer/blob/master/README.md#combined-navigation--content-view

By the way, you don't need to compile the project, you can just download the latest version and run it.

**Comment by omeryanar** [comment] 2023-02-23 19:34
After some bug fixes in the latest v2.0 version, this feature is now complete. So I'm closing this issue.

**Closed by omeryanar** 2023-02-23 19:34 UTC
Labels: enhancement

**Comment by evnb** [comment] 2024-11-29 22:31
This is amazing!! I've been looking for a file explorer that can do this on Windows (It is default behavior in macOS Finder's details view). The main reason I want this ability is so I can select files across multiple folders in the same selection, but right now when I try to add to my selection from another folder, the original selection disappears
![omeryanar_FileExplorer_multiselect](https://github.com/user-attachments/assets/5079220f-fecc-4058-862b-b78c69a339c9)

**Comment by ccwang65** [comment] 2025-04-04 05:05
I dragged the spliter between the navigation pane and the main view to the right most, then the main view is unvisible. How to make it visible again?

![Image](https://github.com/user-attachments/assets/7cea9876-def4-4937-b9df-dc055fda9969)

**Comment by omeryanar** [comment] 2025-04-04 23:04
> -- Finally I find the user.configure in %appdata% and manually decreased the value for "LeftPaneWidth". Great app. Hope to improve to expand %appdata% and other environment variables in the address field for browsing.

That's right, the left and right pane widths are saved in the user.config file. And thanks for the bug report, I reproduced the problem. I think it's necessary to set a minimum width limit for the pane widths.
