### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by jefflord** [omeryanar/FileExplorer#65] opened 2024-02-25 13:04 UTC
I know there was https://github.com/omeryanar/FileExplorer/issues/53, but a very common one that is missing is accessing the location bar. 

Usually this is done with ALT+D, and CTRL+L. I only use ALT+D, but I think people are 50/50 on this. 

Most of normal Windows File Explorer keyboard shortcuts should be implemented, maybe these were missed.

Some of how TAB and ARROW work in this program are pretty unorthodox. You should be able to access all sections with a TAB and ARROW keys to get around in the sections, generally. 

Also, KB navigation within a folder to jump to files is also not working. 

Are these types of things addressable?

**Comment by omeryanar** [comment] 2024-03-05 18:41
I wasn't aware of the shortcuts ALT+D and CTRL+L, I will add them in the next version.

> 
> Also, KB navigation within a folder to jump to files is also not working.
> 

Can you explain this a little more?

**Comment by jefflord** [comment] 2024-03-05 18:59
> I wasn't aware of the shortcuts ALT+D and CTRL+L, I will add them in the next version.

Awesome!


> > Also, KB navigation within a folder to jump to files is also not working.
> Can you explain this a little more?

Sure, if you are in a folder (or any focused panel), and you press a key on the keyboard, it should activate/select each file that starts with that keyboard letter, if one exists. So it "jumps" to the files/folders that start with that letter.

**Comment by omeryanar** [comment] 2024-03-24 09:50
> Sure, if you are in a folder (or any focused panel), and you press a key on the keyboard, it should activate/select each file that starts with that keyboard letter, if one exists. So it "jumps" to the files/folders that start with that letter.

This is implemented in v3.2 (File List should have focus). Keyboard shortcuts are in my todo list.

**Comment by jefflord** [comment] 2024-03-25 11:35
Wow, very nice. This is an interesting implementation. I have some feedback on this version. 

1. It does not select the file, it just focuses the file. You still need to use space to select the file. I think it should select the file so you can skip the "space to select" part. So the usage would be to just use the letter the number of times that's needed to get the to the file, and then Enter to open the file. The "issue" with the way it works now is that using Space to select the focused file, will leave any already selected files selected, and so you might not open the file you think you are using. Basically, it should work like how the default Windows File Explorer works. 
2. With regard to how you have the matched text highlighted, I think that is fantastic. Would it be possible to have an option to allow it to find and select based on two or more characters as a substring? 

Once again, thanks for the quick turn around! Great work.

**Comment by sjtuross** [comment] 2024-03-26 08:17
Is there a keyboard shortcut to do refresh? I tried Ctrl+R and F5 neither of which seems to work. Refresh is also not in the context menu. It took me a while to find the refresh button beside the address bar.

**Comment by jefflord** [comment] 2024-03-26 11:41
> Is there a keyboard shortcut to do refresh? I tried Ctrl+R and F5 neither of which seems to work. Refresh is also not in the context menu. It took me a while to find the refresh button beside the address bar.

[omeryanar](https://github.com/omeryanar) said "Keyboard shortcuts are in my todo list." I guess that one will be included. However, it seems really good at monitoring the folder and not really needing refreshing. 

Do you see a scenario where the files or folders are not refreshed automatically?

**Comment by sjtuross** [comment] 2024-03-26 11:59
Yes. For example, after a file is got renamed, it still shows the old name until I do refresh. I was confused. There are more scenarios. Auto refresh is really needed.

**Comment by omeryanar** [comment] 2024-03-26 12:51
Refresh should only be required on network folders. All changes in local folders are tracked and updated automatically. If this is not the case, can you give some detail about your environment? For example, if your windows is installed in a virtual environment (such as Parallels Desktop on Mac) then change tracking mechanism might not work.

**Comment by sjtuross** [comment] 2024-03-27 03:12
You're right. Local folders work fine. I had to do manual refresh in a mapped network drive. Is there any hidden setting to enable auto refresh on network folders?

**Comment by jefflord** [comment] 2024-03-27 10:39
@sjtuross I see this also. It really should be refreshing these automatically also, but it's not. 

It seems like @omeryanar is implying this is by design. Maybe so, but I think it should monitor these also.

**Comment by omeryanar** [comment] 2024-03-28 14:51
> You're right. Local folders work fine. I had to do manual refresh in a mapped network drive. Is there any hidden setting to enable auto refresh on network folders?

No setting, this issue is a limitation of [FileSystemWatcher](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-8.0) the class responsible for change tracking. It somehow loses the connection and stops sending file/directory change events. I converted issue #60 to a bug, and try to fix it by a recurrent connection refresh.

**Comment by omeryanar** [comment] 2024-03-28 14:55
> @sjtuross I see this also. It really should be refreshing these automatically also, but it's not.
> 
> It seems like @omeryanar is implying this is by design. Maybe so, but I think it should monitor these also.

No, actually not by design. In normal conditions, file system should send change notifications for nerwork drives too,  just like it does for local drives, but somehow it doesn't. I will look into it.

**Comment by omeryanar** [comment] 2024-03-30 15:05
Network drivers update issue has been fixed in the latest version (v3.3). It turns out to be a buffer issue, here is the reason for anyone interested. 

https://stackoverflow.com/questions/9739560/what-is-the-ideal-size-for-filesystemwatcher-internalbuffersize

**Comment by omeryanar** [comment] 2024-03-30 15:15
> Wow, very nice. This is an interesting implementation. I have some feedback on this version.
> 
> 1. It does not select the file, it just focuses the file. You still need to use space to select the file. I think it should select the file so you can skip the "space to select" part. So the usage would be to just use the letter the number of times that's needed to get the to the file, and then Enter to open the file. The "issue" with the way it works now is that using Space to select the focused file, will leave any already selected files selected, and so you might not open the file you think you are using. Basically, it should work like how the default Windows File Explorer works.
> 2. With regard to how you have the matched text highlighted, I think that is fantastic. Would it be possible to have an option to allow it to find and select based on two or more characters as a substring?
> 
> Once again, thanks for the quick turn around! Great work.

1. You are right, it just focuses the file, it also should select the file. I will look into it.
2.  Yes, if you type fast it will search for more characters. If you type one by one, it will jump to the next file containing that character.

**Comment by sjtuross** [comment] 2024-03-30 15:47
I can confirm network drive works in v3.3 and F5 can do refresh. Great work!!

**Comment by jefflord** [comment] 2024-03-30 20:46
> > Wow, very nice. This is an interesting implementation. I have some feedback on this version.
> > 
> > 1. It does not select the file, it just focuses the file. You still need to use space to select the file. I think it should select the file so you can skip the "space to select" part. So the usage would be to just use the letter the number of times that's needed to get the to the file, and then Enter to open the file. The "issue" with the way it works now is that using Space to select the focused file, will leave any already selected files selected, and so you might not open the file you think you are using. Basically, it should work like how the default Windows File Explorer works.
> > 2. With regard to how you have the matched text highlighted, I think that is fantastic. Would it be possible to have an option to allow it to find and select based on two or more characters as a substring?
> > 
> > Once again, thanks for the quick turn around! Great work.
> 
> 1. You are right, it just focuses the file, it also should select the file. I will look into it.
> 2. Yes, if you type fast it will search for more characters. If you type one by one, it will jump to the next file containing that character.

Re 2. Yes, you are correct but that's not the question I asked.  I am asking if we could we add an option to enable searching/highlight and optional selecting based on substrings containing two or more characters?

For instance, with this if I type "S02", I could quickly find/select all the files that have that anywhere in the name.

**Comment by Xiarno** [comment] 2024-05-13 01:10
@omeryanar Would it be possible to add settings to change keyboard shortcut?

Also add the keyboard shortcut CTRL + W which would close the current tab? It's the default chrome shortcut and is extremely useful to quickly create new tab and close it.

**Comment by omeryanar** [comment] 2024-08-12 20:20
> Also add the keyboard shortcut CTRL + W which would close the current tab? It's the default chrome shortcut and is extremely useful to quickly create new tab and close it.

CTRL + W shortcut added in the latest release (v3.5)

**Closed** 2024-08-12 20:24 UTC
Labels: enhancement
